server: 
  port: 9012
spring: 
  application: 
    name: hrm-course
  datasource: 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql:///hrm_course
      username: root
      password: 123456
mybatis-plus: 
  mapper-locations: classpath:com/zc/mapper/*Mapper.xml
  type-aliases-package: com.zc.domain,com.zc.query